command:
  image: node
  command: yarn
  additional_volumes:
    npmrc:
      host: "~/.npmrc"
      container: "/home/riptide/.npmrc"
      type: file
    yarnrc:
      host: "~/.yarnrc"
      container: "/home/riptide/.yarnrc"
      type: file
    yarn:
      host: "~/.yarn"
      container: "/home/riptide/.yarn"
    ssh:
      host: "~/.ssh"
      container: "{{ home_path() }}/.ssh"
      mode: "ro"
