command:
  image: node
  command: npm
  additional_volumes:
    npmrc:
      host: "~/.npmrc"
      container: "/home/riptide/.npmrc"
      type: file
    npm:
      host: "~/.npm"
      container: "/home/riptide/.npm"
    ssh:
      host: "~/.ssh"
      container: "{{ home_path() }}/.ssh"
      mode: "ro"
