command:
    image: riptidepy/php
    command: php
    environment:
      XDEBUG_CONFIG: 'remote_host={{ host_address() }}'
      PHP_IDE_CONFIG: 'serverName=riptide-{{ parent().parent().name }}'
    additional_volumes:
      opcache:
        host: "~/.php_riptide_opcache/xdebug_enabled"
        container: "/opcache"
